name: phenogpt2_user
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cuda-compiler
  - blas
  - ipykernel
  - libfabric
  - libgcc-ng
  - libstdcxx-ng
prefix: /home/nguyenqm/miniconda3/envs/phenogpt2_user
